# Generated by Django 5.1.2 on 2024-11-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='edited',
        ),
    ]
